### ISSUE TITLE
Backup & restore to a new router - The device is disabled by Config entry

### ISSUE THREAD

**Issue by Rowleys** [zigpy/zigpy-znp#111]
Hi all, I have run the backup and restored the config to a new Zigbee router Sonoff 3.0 USB, All the devices are showing but they all say "The device is disabled by Config entry." How do I fix this, please

Thanks

**Comment by puddly** [comment]
Did you disable ZHA and not re-enable it?

**Comment by puddly** [comment]
Closing due to no feedback.

**Comment by Adminiuga** [comment]
Happens if the Core is restarted while ZHA is disabled. Should be fixed in newer versions
