### ISSUE TITLE
syntax for a lan coordinator

### ISSUE THREAD

**Issue by craggus2000** [zigpy/zigpy-znp#126]
hi,
What's the syntax for using a lan coordinator by IP Address please?
I've tried things like py -m zigpy_znp.tools.energy_scan socket://192.168.5.45:6638 but it just produces loads of errors.
If i use a USB coordinator I can use COM4 as the device and it works, but I want to scan with my lan coordinator.
I'm using the tools in windows in a virtual environment if it makes any difference.
Thanks very much

**Comment by tube0013** [comment]
Can you post the output you get?

**Comment by puddly** [comment]
Closing due to no feedback.
