### ISSUE TITLE
SONOFF ZigBee 3.0 USB Dongle Plus - No RSSI values shown

### ISSUE THREAD

**Issue by JMan7777** [zigpy/zigpy-znp#139]
Hi,

I just upgraded my ZHA coordinator from a Nortek HUSBZB-1 stick (Firmware 6.7.8) to a SONOFF ZigBee 3.0 USB Dongle Plus (Firmware CC1352P2_CC2652P_launchpad_coordinator_20220219) using the method described [here](https://github.com/zigpy/zigpy-cli/pull/2).

After the migration all my devices are connected, however there are no RSSI values available anymore. RSSI is shown as N/A (aka Unknown) for all devices. 

Is this a bug in Zigpy or in the Sonoff firmware ?

Thx a lot.

![image](https://user-images.githubusercontent.com/39986400/155687208-ddc90648-45fe-4eec-89cc-39969b377416.png)

![image](https://user-images.githubusercontent.com/39986400/155686878-4405d103-4aea-440e-8636-dd2a6488974a.png)

**Comment by puddly** [comment]
That's normal. RSSI information is not exposed by Z-Stack, only LQI.
