### ISSUE TITLE
ErrorError that I do not understand

### ISSUE THREAD

**Issue by ik1zyq** [zigpy/zigpy-znp#145]
Hello,
i have a 4 channel relay board which is associated via ZHA in HASSOS and it works but i am always in the log the following error you find in the picture, is there a solution to this? thank you
Roberto
![image](https://user-images.githubusercontent.com/98024250/161308237-4a91ac5f-34fe-4814-a9ea-61ca15d42bcf.png)

**Comment by puddly** [comment]
Enable https://www.home-assistant.io/integrations/zha/#debug-logging and post the section of `/config/home-assistant.log` where this error message occurs, this screenshot alone doesn't really have much context.
