### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by lociii** [zigpy/zigpy-znp#52]
```python
2020-12-15 11:28:59 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/zigpy_znp/zigbee/application.py", line 1351, in _discover_route
await asyncio.sleep(0.1 * self._nib.RouteDiscoveryTime)
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```

Seems like RouteDiscoveryTime is not initialized (yet).
Message pops up in the log when restarting HA. Please let me know if you need further information.
As far as I can tell there is no misbehavior caused by this error.

I'm running supervised **Home Assistant 2020.12.0** using a LAUNCHXL-**CC26X2R1**

Thanks for having a look.

**Comment by puddly** [comment]
Hmm. The only way I can see this happening is if requests are sent before `ControllerApplication.startup` has completed.

Can you reliably reproduce this?
