### ISSUE TITLE
[SUGGESTION] Migrate zigpy-znp repository to upstream zigpy organization?

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy-znp#6]
@Adminiuga can I suggest that you please consider having your zigpy-znp repository here on GitHub moved to the zigpy organization @ https://github.com/zigpy/ so that the mainstream copy of this repo will stay there as its upstream instead and owned by the upstream zigpy organization? 

That way all developers that are members in the zigpy organization can have write access to one or more projects that it own for collaboration as a community? 

This would also help new developers take notice of this zigpy-znp project.

Hope that you could all come to an agreement that will make everyone happy with continuing with working on the zigpy-znp repository together without getting offended by any ownership conflicts.

**Comment by Adminiuga** [comment]
Unfortunately I do not have access to zigpy organization on GitHub. I'd like to move all projects under one "roof", but currently don't have the privileges required to do so.

**Comment by Hedda** [comment]
Can maybe GitHub support can help if no one can contact @rcloran about this so that he can give more people has administrator privileges to the zigpy organization @ https://github.com/zigpy/ or? 

This suggestion also relates to https://github.com/zigpy/zigpy/issues/113

**Comment by Hedda** [comment]
Time for zigpy-znp repo migration to zigpy organization now that you are co-owner/co-admin?

Move repo from https://github.com/zha-ng/zigpy-znp to https://github.com/zigpy/zigpy-znp

**Comment by Adminiuga** [comment]
zigpy-znp is in early stages and is not even working, so it is not ready to be publicly released. I pushed it there just to "capture" the name, but other than that there's a lot of work to be done.

**Comment by Neustradamus** [comment]
@Adminiuga: It is possible to see for the transfer?

**Comment by puddly** [comment]
@Neustradamus: I only started using this module a few days ago with my CC26X2R1. With a single tester, I don't think zigpy-znp is ready for anything just yet 😄. Maybe in a week or two, when I bring code coverage closer to 100% and get it running smoothly with my network.

**Comment by Neustradamus** [comment]
You can move without problems, redirections will be here...

**Comment by Hedda** [comment]
@Neustradamus I believe that the issue is probably that for now, they would prefer the stealth approach so that they don't expose zigpy-znp to discovery by normal-users when it not ready for general testing, ...and that way they also avoid getting requests from annoying by people like myself ;)

IMHO once ready for testing by advanced-users, it would benefit to move this project as it has then hopefully the possibility to not only attract advanced-users but also more developers that can help :)

**Comment by Adminiuga** [comment]
Yep, I don't have issues moving this to zigpy in near the future once it is more or less ready for general use.

**Comment by Hedda** [comment]
@Adminiuga & @puddly I just noticed that zigpy-znp (v0.1.1) will be supported soon by the upcoming Home Assistant so will that library be considered to be included into zigpy organization and as such have its repository moved to https://github.com/zigpy or?

https://github.com/zigpy

These PyPI package projects/links remain the same however might need to make sure that the "Maintainers" there are up-to-date:

https://pypi.org/project/zigpy-znp/

https://pypi.org/project/zigpy/

PS: @puddly & @Adminiuga Congratulations on the milestone of adding zigpy-znp support to Home Assistant ZHA integration!

https://github.com/home-assistant/core/pull/39700

https://github.com/zha-ng/zigpy-znp

**Comment by basnijholt** [comment]
Perhaps it makes sense to move this repo now?

**Comment by puddly** [comment]
I've created a PR for this https://github.com/zha-ng/zigpy-znp/pull/45. Hopefully Travis CI and Coveralls will accept the new URLs without any problems.

Will a redirect be created from https://github.com/zha-ng/zigpy-znp/ to https://github.com/zigpy/zigpy-znp/ ?

**Comment by Adminiuga** [comment]
yes, GH is really good with redirects. So old URL would lead to new location anyway

**Comment by Neustradamus** [comment]
Thanks all for your changes :)

Maybe, you can see for other repositories too?
- https://github.com/zha-ng

You can show your profile in public (by default it is not):
- https://github.com/orgs/zigpy/people

**Comment by Hedda** [comment]
> You can show your profile in public (by default it is not):
> 
> * https://github.com/orgs/zigpy/people

Yes no people are currently listed zigpy org https://github.com/orgs/zigpy/people but are in https://github.com/orgs/zha-ng/people
