### ISSUE TITLE
Migration CC2531 to CC2652R (zzh) inside LXC

### ISSUE THREAD

**Issue by chrismast** [zigpy/zigpy-znp#70]
He, first of all, great tool.
I was just about to migrate from my CC2531 to a new zzh stick and in time saw your tool that could simplify the migration a lot.
Currently, I am running zigbee2mqtt inside a Proxmox LXC and passed-through my USB devices.
Both show up under lsusb in /dev/ttyACM0 (CC2531) and /dev/ttyUSB0 (CC2652R).
I can also do the initial backup of the CC2531 and the backup file is generated using the following command:

> sudo python3 -m zigpy_znp.tools.network_backup /dev/ttyACM0 -o network_backup.json

Now when I try to restore the backup config to /dev/ttyUSB0 I get an error message though as following (with -v enabled):

> sudo python3 -m zigpy_znp.tools.network_restore /dev/ttyUSB0 -i network_backup.json -v

![image](https://user-images.githubusercontent.com/63285062/114259143-0fbd4980-99f6-11eb-98a8-f13ae6d55ba5.png)

The zzh stick seems to work correctly as when I run the test.py script it returns the following:

```
Got 7 bytes in response to PING command: b'\xfe\x02a\x01Y\x06='
PASS|OK

```

Any advice on how to fix this?

**Comment by puddly** [comment]
Hmm. Your CC2652R seems to be getting stuck during network formation. Does this happen after you unplug/plug in the stick and try the restore again?

The "PING" test is actually one of the first commands sent by zigpy-znp (run the tool with `-vv` to see the UART bytes) so that command line tool doesn't tell you any extra info:

```Python
2021-04-09 11:20:26.856 computer zigpy_znp.api DEBUG Testing connection to /dev/cu.usbserial-1420
2021-04-09 11:20:26.856 computer zigpy_znp.api DEBUG Sending request: SYS.Ping.Req()
2021-04-09 11:20:26.857 computer zigpy_znp.uart TRACE Sending data: b'\xFE\x00\x21\x01\x20'
2021-04-09 11:20:26.862 computer zigpy_znp.uart TRACE Received data: b'\xFE\x02\x61\x01\x59\x06\x3D'
2021-04-09 11:20:26.862 computer zigpy_znp.api DEBUG Received command: SYS.Ping.Rsp(Capabilities=<MTCapabilities.APP_CNF|GP|UTIL|ZDO|AF|SYS: 1625>)
```

**Comment by chrismast** [comment]
> Hmm. Your CC2652R seems to be getting stuck during network formation. Does this happen after you unplug/plug in the stick and try the restore again?

Just tried it as per your comment, did the following:

1) unplug the CC2652R
2) restarted the LXC
3) did a `chmod o+rw /dev/ttyUSB0` on the Proxmox host to set permissions
4) run above command again, same error though

Output with -vv:

![image](https://user-images.githubusercontent.com/63285062/114259422-07fea480-99f8-11eb-884b-57a447b33da0.png)

Beginning with ping:

![image](https://user-images.githubusercontent.com/63285062/114259445-26fd3680-99f8-11eb-801d-18c1e4efd739.png)

```2021-04-10 12:25:54.684 mosquitto zigpy_znp.nvram DEBUG Read NVRAM[NvSysIds.ZSTACK][ExNvIds.TCLK_TABLE][0x0000] = b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xFF\x00\x00\x00'
2021-04-10 12:25:54.684 mosquitto zigpy_znp.api DEBUG Detected Z-Stack 3.3
2021-04-10 12:25:54.684 mosquitto zigpy_znp.api DEBUG Connected to /dev/ttyUSB0 at 115200 baud
```

**Comment by puddly** [comment]
If it's a noisy RF environment, the stick could be refusing to form a network. I've seen it happen with CC2531s more than the zzh but anything is possible with TI's Z-Stack. Try unscrewing the antenna and try the restore once more?

If that still doesn't work, check over your CC2531 backup. If your network key is `01030507090b0d0f00020406080a0c0d`, you don't really have any secret info in the backup other than the IEEE addresses of the devices on your network (they're only unique, not really "secret") so if you don't mind posting the backup JSON here, I can just run the restoration locally and upload an NVRAM state that you can restore directly to your stick via `python -m zigpy_znp.tools.nvram_write -i nvram_backup.json /dev/...`. It bypasses network formation and should "just work".

In the future I'm hoping to have zigpy-znp directly set the network up in NVRAM without asking TI's Z-Stack to form it so this won't be an issue. But until then...

**Comment by chrismast** [comment]
> If it's a noisy RF environment, the stick could be refusing to form a network. I've seen it happen with CC2531s more than the zzh but anything is possible with TI's Z-Stack. Try unscrewing the antenna and try the restore once more?
> 
> If that still doesn't work, check over your CC2531 backup. If your network key is `01030507090b0d0f00020406080a0c0d`, you don't really have any secret info in the backup other than the IEEE addresses of the devices on your network (they're only unique, not really "secret") so if you don't mind posting the backup JSON here, I can just run the restoration locally and upload an NVRAM state that you can restore directly to your stick via `python -m zigpy_znp.tools.nvram_write -i nvram_backup.json /dev/...`. It bypasses network formation and should "just work".
> 
> In the future I'm hoping to have zigpy-znp directly set the network up in NVRAM without asking TI's Z-Stack to form it so this won't be an issue. But until then...

That seemed to have done the trick, I unscrewed the antenna and the restore did run through all the way without error.
Adjusted my configuration.yaml, started zigbee2mqtt and did some mqtt commands, all working so far.

Thanks for the help! Will revert if anything else comes up.

**Comment by puddly** [comment]
Glad that worked, I'll make the error message a little more descriptive.
