### ISSUE TITLE
Wrong device status

### ISSUE THREAD

**Issue by erkr** [zigpy/zigpy-znp#78]
When I e.g. manually operate my outlet plug by pressing the physical button to toggle one-off (I.e. Innr SP120, but don't think it matters much), the state change isn't propagated back to home assistant.
I'm new using ZHA with a CC2531 adapter, but on a HUE Bridge the state is updated after a while (not instantly, so status is most likely polled).

**Comment by puddly** [comment]
While this is a different device, I believe you're affected by the same problem: https://github.com/zigpy/zha-device-handlers/issues/605

**Comment by erkr** [comment]
Thanks for pointing to that issue. Not sure it is the same issue. I will verify with a Philips power plug without energy measurement functions and share the outcome.

**Comment by erkr** [comment]
Today I verified the behavior with a Philips Smart Plug (no energy measurement options). That device behaves normal! So when operating the physical on/off button, the state in the Home Assistant app immediately changes accordingly. So it seems indeed a specific SP 120 problem as discussed in  zigpy/zha-device-handlers#605. Puddly, thx for referring that issue

**Comment by erkr** [comment]
Today I replaced the CC2531 with a Conbee 2. With the conbee 2, the manual operation of the power button on the SP120 plug properly propagates back to HA as well.
So this issue is NOT related to the issue zigpy/zha-device-handlers#605. That issue described there with the energy meter stays unknown and that issue is also applicable with the Conbee 2.
