### ISSUE TITLE
Bump pyserial-asyncio to version 0.6 release as contain fix for Windows OS

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy-znp#88]
This needs testing to confirm first, but FY:

pyserial-asyncio version 0.6 has now finally been released with a fix for Windows OS:

https://github.com/pyserial/pyserial-asyncio/releases/tag/v0.6

https://pypi.org/project/pyserial-asyncio/#history

pyserial-asyncio 0.6 includes "fix multiple writers race on windows"

https://github.com/pyserial/pyserial-asyncio/pull/70

Which solves "Never transmits on Windows in version 0.5"

https://github.com/pyserial/pyserial-asyncio/issues/69

The backstory is pyserial-asyncio version 0.5 was broken/blacklisted on Windows OS.

```
    install_requires=[
        'pyserial-asyncio; platform_system!="Windows"',
        'pyserial-asyncio!=0.5; platform_system=="Windows"',  # 0.5 broke writes
        "zigpy>=0.37.0",
``

**Comment by MattWestb** [comment]
First sorry for that HA was closing the issue adding this in HA.

I have running all my test network (with EZSP radios) but not with local comports in docker containers under windows (for the moment ESPHome with EZSP or tuya ZBGW over Eth) and its working OK only that windows host is not supporting local comports (that i think is false you need mapping it as WSL and not the normal comX in windows (and having this component updated).

I also running HA Supervised on my Pi3B+ that is also not supported but is working very well and if i getting problem i downloading the OS and restoring the backup and its shall not being any problem at all.

From my point of view is better rolling this fix in all Zigpy libs then its being in phase with the main Python and is if its fixing more problems and also is doing that some radios working OK under windows i think is on win win situation (and what AH is doing there own story). 

HA/ZHA is still not recommended but possible running under native windows so no real support for the platform is not possible but for beginners and testing i think it great having it working but not 110% supported (like is today).

**Comment by MattWestb** [comment]
Thanks puddly you the man !!

PS dont tell HA frenck then hi have baned this ;-))
